
WEBUI_DIRECTORY: ./.test

SD15_MODEL_DIRECTORY: $WEBUI_DIRECTORY$/models/Stable-diffusion/
SD15_CONTROL_NET_DIRECTORY: $WEBUI_DIRECTORY$/models/ControlNet/
EXTENSION_DIRECTORY: $WEBUI_DIRECTORY$/extensions/
SD15_TEXTUAL_INVERSION_DIRECTORY: $WEBUI_DIRECTORY$/embeddings/
LORA_DIRECTORY: $WEBUI_DIRECTORY$/models/Lora/
REPOSITORIES_DIRECTORY: $WEBUI_DIRECTORY$/repositories/



