
WEBUI_DIRECTORY: /workspace/stable-diffusion-webui/

SD15_MODEL_DIRECTORY: $WEBUI_DIRECTORY$/models/Stable-diffusion/SD1.5
SDXL_MODEL_DIRECTORY: $WEBUI_DIRECTORY$/models/Stable-diffusion/SDXL
SD15_CONTROL_NET_DIRECTORY: $WEBUI_DIRECTORY$/models/ControlNet/
EXTENSION_DIRECTORY: $WEBUI_DIRECTORY$/extensions/
SD15_TEXTUAL_INVERSION_DIRECTORY: $WEBUI_DIRECTORY$/embeddings/
LORA_DIRECTORY: $WEBUI_DIRECTORY$/models/Lora/
REPOSITORIES_DIRECTORY: $WEBUI_DIRECTORY$/repositories/



