base_model_Stable_diffusion:
  name: Stable Diffusion SDXL
  description: Main Stable Diffusion XL V1.0 checkpoint
  files:
    - main:
        url: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/unet/diffusion_pytorch_model.safetensors"
        path: "$SDXL_MODEL_DIRECTORY$/SDXL_V1.0.safetensors"
    - SDXL_V1.0_offset:
        url: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors"
        path: "$LORA_DIRECTORY$/SDXL_V1.0_offset.safetensors"
    - SDXL_V1.0_refiner:
        url: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors"
        path: "$SDXL_MODEL_DIRECTORY$/SDXL_V1.0_refiner.safetensors"
    - SDXL_V1.0_vae:
        url: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors"
        path: "$SDXL_MODEL_DIRECTORY$/SDXL_V1.0.vae.safetensors"
  default: True

Anime_Art_Diffusion_XL:
  name: Anime Art Diffusion XL
  description: 
    Raising from the ashes of ArtDiffusionXL-alpha, this is the first anime
    oriented model I make for the XL architecture. It will serve as a good 
    base for future anime character and styles loras or for better base models.

    Should work well around 8-10 cfg scale and I suggest you don't use the SDXL
     refiner, but instead do a i2i step on the upscaled image (like highres fix).

    It's trained on multiple famous artists from the anime sphere (so no stuff
    from Greg Rutkowsky, but stuff like Sam Yang and Wlop for example). The 
    model is oriented at producing stylized results. I also suggest you use
    words like 8k and high resolution because otherwise it tends to go too
    much low detail. Look at the examples.

  files:
    - main:
        url: "https://civitai.com/api/download/models/127055?type=Model&format=SafeTensor&size=full&fp=fp16"
        path: "$SDXL_MODEL_DIRECTORY$/SDXL_Anime_Art.safetensors"
  default: False

DreamShaper:
  name: DreamShaper XL1.0 Alpha2
  description: 
    Finetuned over SDXL1.0.
    Even if this is still an alpha version, I think it's already much better
    compared to the first alpha based on xl0.9. For the workflows you need 
    Math plugins for comfy (or to reimplement some parts manually).
    Basically I do the first gen with DreamShaperXL, then I upscale to 2x 
    and finally a do a img2img steo with either DreamShaperXL itself, or a 
    1.5 model that i find suited, such as DreamShaper7 or AbsoluteReality.

    What does it do better than SDXL1.0?

        - No need for refiner. Just do highres fix (upscale+i2i)

        - Better looking people

        - Less blurry edges

        - 75% better dragons 🐉

        - Better NSFW

  files:
    - main:
        url: "https://civitai.com/api/download/models/126688?type=Model&format=SafeTensor&size=full&fp=fp16"
        path: "$SDXL_MODEL_DIRECTORY$/SDXL_DreamShaper.safetensors"
  default: False
